[build]
  functions = "serverless"
  publish = "public"

[dev]
  functions = "serverless"
  publish = "public"
  framework = "#static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Header-Source = "netlify.toml"

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Header-Source = "netlify.toml"
